// src/angular/optimized-image.component.ts
import { Component, Input } from '@angular/core'
import { optimizeImage } from '@/optimizer'

@Component({
  selector: 'app-optimized-image',
  template: `<img [src]="optimizedSrc" [alt]="alt" [width]="width" [height]="height" />`
})
export class OptimizedImageComponent {
  @Input() src!: string
  @Input() alt: string = ''
  @Input() quality: number = 80
  @Input() width: number = 800
  @Input() height: number = 600
  @Input() format: string = ''

  get optimizedSrc() {
    return optimizeImage(this.src, {
      quality: this.quality,
      width: this.width,
      height: this.height,
      format: this.format
    })
  }
}

// src/react/OptimizedImage.tsx
import React from 'react'
import { optimizeImage } from '@/optimizer'

interface OptimizedImageProps {
  src: string
  alt?: string
  quality?: number
  width?: number
  height?: number
  format?: string
}

const OptimizedImage: React.FC<OptimizedImageProps> = ({
  src,
  alt = '',
  quality,
  width,
  height,
  format
}) => {
  const optimizedSrc = optimizeImage(src, { quality, width, height, format })

  return <img src={optimizedSrc} alt={alt} width={width} height={height} />
}

export default OptimizedImage
